Add Walkthrough, add examiner view, smoother animations and sound FX.
Tumo-Product/time-signature pull request #2
Opened 2022-05-20 13:25 UTC by HaykAvagyan1

2022-05-23 07:41 UTC, tumochristine requested changes
This looks good! Other than the two comments I left, I also have two general requests:

1) Reformat the commit messages:
- Use active voice in the title (“Implement walkthrough” instead of “walkthrough done”)
- Make sure all the commits have a description (the first two commits don’t)
- If you say “fix x bug”, describe the bug you fixed.


2) I tried to pull the repo locally but was getting some conflicts with the build file. Are you getting these? Do you need to build again?
![Screen Shot 2022-05-23 at 10 29 00 AM](https://user-images.githubusercontent.com/102517998/169768501-9c4d74a1-1d70-4ebf-8936-c2b717741306.png)

2022-05-23 07:41 UTC, tumochristine commented on src/modules/managers/AudioManager.js
> +        return sources;
I believe we can rewrite lines 34 - 40 as:

```return AudioManager.tracks.map(track => track.src);```

2022-05-24 06:50 UTC, HaykAvagyan1 commented on src/modules/components/Signature.js
> +                let waitTime = upperElement.animate(signature); lowerElement.animate(signature);
waitTime returns a promise so you can await this function, then set a number.

2022-05-24 07:02 UTC, HaykAvagyan1 commented on src/modules/components/Signature.js
> +                let waitTime = upperElement.animate(signature); lowerElement.animate(signature);
I can eliminate this variable and await only one of the functions(let's say the left digital number, since they are going at the same time I only want to await one time)

2022-05-24 08:53 UTC, HaykAvagyan1 commented on src/modules/managers/AudioManager.js
> +        return sources;
Done.

2022-05-24 13:06 UTC, merged